### ISSUE TITLE
Desktop icons disappear or become unclickable

### ISSUE THREAD

**Issue by KloudKoder** [budgie-desktop/budgie-desktop#1082]
**Operating System**: Solus 2017.04.18.0
**Budgie version**: v10.3.1-404-g128a50a

**The issue encountered**

Sometime recently, my laptop starting failing to boot about 20% of the time. More accurately, it would get all the way to the Budgie desktop, but no panel icons would be clickable. Occasionally, the icons would not appear at all, leaving only the mouse cursor.

The only way out of this is Ctrl+Alt+F11. But then, there's no way out of that apart from "sudo poweroff". 

**Steps to reproduce the issue**

Boot a bunch of times until you see the issue. Sorry I can't be more specific.

**Comment by KloudKoder** [comment]
When the icons appear in the top left of the desktop as normal, but are unclickable, try the following: Right-click on the desktop. Lower the screen resolution. Then right-click on the desktop again. Restore the original resolution. Now the icons completely disappear.

**Comment by KloudKoder** [comment]
I'm still needing to reboot excessively due to this issue. So far nothing seems to have suppressed it. I should add that I'm using a recent mobile Intel video chipset. It seems that the most common failure mode is booting up to a mouse pointer, which the correct Solus screen background, but absolutely no other UI features whatsoever. Rarely, I do get a full taskbar, but all the launch icons are squished together to the point of being unrecognizable. In either case, the only way out is to use a hotkey combination to bring up a terminal, then "sudo poweroff".

**Comment by KloudKoder** [comment]
In what appears to be yet another manifestation of this bug (which now plagues maybe 1 in 4 boots), the taskbar is rendered properly, but remains unclickable, as though Budgie (Solus?) forgets where it's located. The telltale sign is that the image of the clock freezes, allowing the displayed time in the corner of the screen to lose sync with reality. On the next boot, the time is correct again. It's as though there's a sudden disconnect between the internal notion of screen coordinates, and the GUI itself.

**Comment by KloudKoder** [comment]
This _seems_ to have been fixed by some update. Of course since I don't know how to trigger it reliably, I can't be sure.

**Comment by KloudKoder** [comment]
I was wrong. This is still happening, albeit less frequently. There is no workaround, so I have to power down when it occurs.

**Comment by odonnellnoel** [comment]
This is happening to me!!

Oh the humanity! - Such a perfect OS only to be blighted by a bug like this!

FIX!!!!!

**Comment by nihique** [comment]
I also have this issue :( There are couple of other issues I have with my Dell XPS 9550. This laptop has 4k screen, which can be probably one of the reasons. Should I create new issue for each of them? Solus is otherwise my favorite distro.

**Comment by kichooo** [comment]
This issue is still happening. I get it every 2-3 boots on my Thinkpad with Intel drivers. I never get it on my desktop with NVIDIA. No idea if this piece of information is of any help.

**Comment by KloudKoder** [comment]
I have a feeling that all these are related by improper or incomplete entry/exit to/from idle or sleep (S1 or S3):

#463
solus-project/budgie-desktop#1374
solus-project/budgie-desktop#1082
#466

bwat47's workarounds in the first 2 appear to be effective for me, although it's hard to be sure because these bugs don't occur every time, and might literally depend on the temperature.

Secondly, here's what to do if you come back to a messed up screen or a crazy mouse pointer. Just to be on the safe side, save everything before you test this:

    Push Ctrl+Alt+F11
    Wait until the screen settles down, usually to black or some weird error message
    Push Alt+F2
    Wait til the desktop restores
    If still abnormal try this all again

These key combos seem to be hardwired into GNOME. I actually discovered the first one by accident, and didn't know to get out of it. Unfortunately, there's no way to turn them off under the keyboard settings, so it's an accident waiting to happen (and who would guess that Alt+F2 is the way to undo it?!). But now, these "features" are you friends because they protect you from the disaster that is bad sleep/wake behavior.

One final hunch is that all this points back to quality problems with the Intel video driver. This is a compelling theory based on a lot of reading, but I have no proof. Indeed, on every single boot, my login screen goes crazy with video problems, likely due to the same underlying bug.

**Comment by kwalker99** [comment]
Same issue here, latest Ubuntu Budgie same issues as seen on Solus. The icons appear but are unclickable, the desktop right menu has changed from the full menu to a simple menu with two entries, Budgie Desktop Settings and System Settings. Basically the Budgie desktop isn't running, similar to what i experienced a few years back running Gnome but with Nemo as the file manager and desktop.
