### ISSUE TITLE
Budgie Panel teleporting on menu click

### ISSUE THREAD

**Issue by Flat** [budgie-desktop/budgie-desktop#634]
Arch Linux Kernel 4.7.6
Budgie 10.2.7 ce609910d7678e8f51e60f09d4cf9c10f77f4b39

Occasionally budgie-panel will move itself to the top of the screen with a small margin upon clicking the menu button.

![2016-10-03-11 23 36](https://cloud.githubusercontent.com/assets/2048861/19043006/4f724c1a-895c-11e6-88a1-2c902060854c.png)

 ...

1) Click the menu button

 ...
After killing budgie-panel and its automatic relaunching it works fine until reboot.

**Comment by ikeydoherty** [comment]
Is this GNOME 3.22?

**Comment by Flat** [comment]
Yes it is.

**Comment by haevalencia** [comment]
It happens to me the same thing but using the panel in the bottom, especially when I change the panel size manually, place the panel changes or disappears.

**Comment by ikeydoherty** [comment]
The bottom panel issue is entirely different. This one is GTK3.22 being on crack.

**Comment by haevalencia** [comment]
Ok. Im using manjaro with gnome 3.22

**Comment by Flat** [comment]
Just wanted to add that this is in the logs when the teleport happens
```
budgie-wm.desktop[1689]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x1000007 (budgie-pan)
```

**Comment by Coeur-Noir** [comment]
I've seen the same behaviour with panels in Budgie-Remix Ubuntu 16.10.
Moving it to another position and moving it back fixed the margin.

**Comment by nikp123** [comment]
Bug still present in ArchLinux. (Kernel 4.8.13-1)

**Comment by ikeydoherty** [comment]
Nobody said it was fixed, doesn't need bumping. :)

**Comment by nikp123** [comment]
@ikeydoherty Nevermind, I thought it was fixed because the issue was closed. Disregard my comment.

**Comment by ikeydoherty** [comment]
Still open :)

**Comment by JannikHv** [comment]
Hey guys, long time no see in here :P

I've just updated my Arch system (now on **Budgie-Desktop 10.3.1**) and the teleporting bug just completely dissapeared, was that intentional? Is it the same on Solus?

**Comment by JoshStrobl** [comment]
Closing. If this isn't resolved with Budgie 10.3.1, feel free to comment.

**Comment by Flat** [comment]
Still not resolved

```
May 04 17:43:47 megumin budgie-panel.desktop[4679]: [5631:5680:0504/174347.421983:ERROR:upload_data_presenter.cc(77)] Not implemented reached in virtual void extensions::RawDataPresenter::FeedNext(const net::UploadElementReader&)
May 04 17:46:22 megumin budgie-panel.desktop[4679]: [5631:5680:0504/174622.343914:ERROR:upload_data_presenter.cc(77)] Not implemented reached in virtual void extensions::RawDataPresenter::FeedNext(const net::UploadElementReader&)
May 04 17:47:24 megumin budgie-wm.desktop[4596]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400007 (budgie-pan)
May 04 17:47:24 megumin budgie-panel.desktop[4679]: DiscordCanary 0.0.15
May 04 17:47:38 megumin budgie-wm.desktop[4596]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2400007 (budgie-pan)
```

![2017-05-04-17 48 14](https://cloud.githubusercontent.com/assets/2048861/25726523/9fb58406-30f2-11e7-896a-2ad4d83cd8a9.png)

**Comment by ikeydoherty** [comment]
This has been fixed by replacing `GtkPopover` with our own `BudgiePopover` in git, and will be available shortly in the next release.
